// Parity gate: the TypeScript engine must reproduce the canonical pytides2
// output (scripts/tides.py) within tide-table tolerance. Reference vectors are
// generated by tools/gen-reference.py — regenerate them if you change stations.
//
//   npm run test:engine

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

import { Tide } from './predict';
import type { StationData, TideEvent } from './predict';

const here = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.join(here, '..', '..', 'assets', 'data');
const reference = JSON.parse(
  readFileSync(path.join(here, '__fixtures__', 'reference.json'), 'utf8'),
) as {
  windows: {
    station: string;
    t0: string;
    spanHours: number;
    hourly: number[];
    extrema: { t: string; h: number; type: 'high' | 'low' }[];
  }[];
};

// Tolerances: tighter than a printed tide table.
const HEIGHT_TOL_M = 0.02; // hourly height match
const EVENT_TIME_TOL_S = 120; // high/low water timing
const EVENT_HEIGHT_TOL_M = 0.03; // high/low water height

function loadStation(file: string): StationData {
  return JSON.parse(readFileSync(path.join(dataDir, file), 'utf8'));
}

for (const w of reference.windows) {
  const label = `${w.station} @ ${w.t0}`;
  const t0 = new Date(`${w.t0}Z`); // pytides uses naive-UTC
  const tide = new Tide(loadStation(w.station));

  test(`hourly heights match pytides — ${label}`, () => {
    const times = Array.from(
      { length: w.spanHours + 1 },
      (_, i) => new Date(t0.getTime() + i * 3600_000),
    );
    const heights = tide.heightsAt(times);
    let maxErr = 0;
    for (let i = 0; i < heights.length; i++) {
      maxErr = Math.max(maxErr, Math.abs(heights[i] - w.hourly[i]));
    }
    assert.ok(
      maxErr <= HEIGHT_TOL_M,
      `max hourly height error ${maxErr.toFixed(4)} m exceeds ${HEIGHT_TOL_M} m`,
    );
  });

  test(`high/low waters match pytides — ${label}`, () => {
    const t1 = new Date(t0.getTime() + w.spanHours * 3600_000);
    const events: TideEvent[] = tide.extrema(t0, t1);

    assert.equal(
      events.length,
      w.extrema.length,
      `event count ${events.length} != reference ${w.extrema.length}`,
    );

    for (const ref of w.extrema) {
      const refTime = new Date(`${ref.t}Z`).getTime();
      // nearest same-type event
      let best: TideEvent | null = null;
      let bestDt = Infinity;
      for (const e of events) {
        if (e.type !== ref.type) {
          continue;
        }
        const dt = Math.abs(e.time.getTime() - refTime);
        if (dt < bestDt) {
          bestDt = dt;
          best = e;
        }
      }
      assert.ok(best, `no ${ref.type} event near ${ref.t}`);
      const dtS = bestDt / 1000;
      const dh = Math.abs((best as TideEvent).height - ref.h);
      assert.ok(
        dtS <= EVENT_TIME_TOL_S,
        `${ref.type} @ ${ref.t}: time off by ${dtS.toFixed(0)} s (> ${EVENT_TIME_TOL_S})`,
      );
      assert.ok(
        dh <= EVENT_HEIGHT_TOL_M,
        `${ref.type} @ ${ref.t}: height off by ${dh.toFixed(4)} m (> ${EVENT_HEIGHT_TOL_M})`,
      );
    }
  });
}
